//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by com.rc
//
#define IDD_MAIN                        1
#define IDD_DAC_CONST                   2
#define IDD_ADC_CONST                   3
#define IDD_SERVO_CONTROL               4
#define IDD_ABOUTBOX                    5
#define IDM_CONNECTION_DISCONNECT       6
#define IDM_CONNECTION_SETINGS          7
#define IDM_SERVO_CONTROL               8
#define ID_HELP_ABOUT                   9
#define IDD_MODBUS_TIMEOUT              10
#define IDC_IPADDRESS                   11
#define IDC_EDIT_TCP_PORT               12
#define ID_DAC_DAC0_DIRECTACCESS        13
#define ID_DAC_DAC0_000VTO1000V         14
#define ID_DAC_DAC1_DIRECTACCESS        15
#define ID_DAC_DAC1_000VTO1000V         16
#define IDC_EDIT_DAC0_VALUE             17
#define IDC_EDIT_DAC1_VALUE             18
#define IDI_IDE                         19
#define IDR_MENU_MAIN                   20
#define IDC_COMBO_PORT                  21
#define IDC_BUTTON_CONNECT              22
#define IDC_COMBO_SLAVE_ID              23
#define IDC_STATIC_ACCELERATION         24
#define IDC_STATIC_MAX_SPEED            25
#define IDM_RUN                         26
#define IDC_STATIC_MAX_PID_OUT          27
#define IDM_STOP                        28
#define IDC_STATIC_ACCELERATION2        29
#define IDM_MODBUS_TIMEOUT              30
#define IDC_IS_RUN                      31
#define IDC_EDIT_MODBUS_TIMEOUT         32
#define IDC_STATIC_ENC0_ANGLE           32
#define IDC_BUTTON_READ_MODBUS_TIMEOUT  33
#define IDC_BUTTON_WRITE_MODBUS_TIMEOUT 34
#define IDC_STATIC_HALL_POS             34
#define IDC_CHECK1                      35
#define IDC_STATIC_ENCODER0_RAW         35
#define IDC_STATIC_ENC1_ABS_POS         36
#define IDC_EDIT_ENC0_OFFSET            37
#define IDC_BUTTON_ENC0_GET_OFFSET      38
#define IDC_BUTTON_ENC0_SET_OFFSET      39
#define IDC_STATIC_POS_ERROR            41
#define IDC_STATIC_RPM_M                42
#define IDC_STATIC_RPM_T                43
#define IDC_STATIC_RPM_MT               44
#define IDC_STATIC_RPM_T_RAW            45
#define IDC_STATIC_RPM_M_RAW            46
#define IDC_STATIC_RPM_MT_RAW           47
#define IDC_STATIC_RPM_MT2              48
#define IDC_STATIC_TEMP                 48
#define IDC_STATIC_TEMP_32              48
#define IDC_STATIC_MCU_RPM              49
#define IDC_STATIC_SP_SPEED             49
#define IDC_STATIC_SP_POS_TIM8          50
#define IDC_STATIC_POS_ERROR_MIN        51
#define IDC_STATIC_POS_ERROR_MAX        52
#define IDM_CONNECTION_COMSELECT_COM1   201
#define IDM_CONNECTION_COMSELECT_COM2   202
#define IDM_CONNECTION_COMSELECT_COM3   203
#define IDM_CONNECTION_COMSELECT_COM4   204
#define IDM_CONNECTION_COMSELECT_COM5   205
#define IDM_CONNECTION_COMSELECT_COM6   206
#define IDM_CONNECTION_COMSELECT_COM7   207
#define IDM_CONNECTION_COMSELECT_COM8   208
#define IDM_CONNECTION_TCP_IP           209
#define IDD_TCP_SETINGS                 210
#define IDC_STATIC_KP                   301
#define IDC_STATIC_KI                   302
#define IDC_STATIC_KD                   303
#define IDC_STATIC_MAX_I_TERM           304
#define IDC_EDIT_POSITION_PID_P_FACTOR  305
#define IDC_EDIT_POSITION_PID_I_FACTOR  306
#define IDC_EDIT_POSITION_PID_D_FACTOR  307
#define IDC_EDIT_POSITION_PID_MAX_I_TERM 308
#define IDC_STATIC_VELOCITY             309
#define IDC_STATIC_VELOCITY2            310
#define IDC_EDIT_POSITION_PID_SCALE     311
#define IDC_STATIC_POSITION_PID_SCALE   312
#define IDC_BUTTON_WRITE_POSITION_PID_P_FACTOR 320
#define IDC_BUTTON_WRITE_POSITION_PID_I_FACTOR 321
#define IDC_BUTTON_WRITE_POSITION_PID_D_FACTOR 322
#define IDC_BUTTON_WRITE_POSITION_PID_MAX_I_TERM 323
#define IDC_BUTTON_READ_POSITION_PID_SETINGS 324
#define IDC_BUTTON_POSITION_PID_WRITE_ALL 325
#define IDC_BUTTON_WRITE_POSITION_PID_SCALE 326
#define IDC_STATIC_ENCODER              400
#define IDC_EDIT_NEW_POSITION           401
#define IDC_EDIT_SET_VELOCITY           402
#define IDC_EDIT_SET_ACCEL              403
#define IDC_EDIT_SET_ACCELERATION       403
#define IDC_EDIT_SET_MAX_SPEED          404
#define IDC_EDIT_MAX_PID_OUT            405
#define IDC_BUTTON_WRITE_NEW_POSITION   406
#define IDC_BUTTON_WRITE_VELOCITY       407
#define IDC_BUTTON_WRITE_ACCEL          408
#define IDC_BUTTON_WRITE_MAX_SPEED      409
#define IDC_BUTTON_WRITE_MAX_PID_OUT    410
#define IDC_BUTTON_SP_POSITION_READ_ALL 411
#define IDC_BUTTON_SP_POSITION_WRITE_ALL 412
#define IDC_EDIT_SET_MAX_VELOCITY2      413
#define IDC_BUTTON_WRITE_MAX_ACC2_AND_VELOCITY2 414
#define IDC_EDIT_SET_ACCELERATION2      415
#define IDC_I0                          1000
#define IDC_I1                          1001
#define IDC_I2                          1002
#define IDC_I3                          1003
#define IDC_I4                          1004
#define IDC_I5                          1005
#define IDC_I6                          1006
#define IDC_I7                          1007
#define IDC_I8                          1008
#define IDC_I9                          1009
#define IDC_Q0                          1010
#define IDC_Q1                          1011
#define IDC_Q2                          1012
#define IDC_Q3                          1013
#define IDC_Q4                          1014
#define IDC_Q5                          1015
#define IDC_Q6                          1016
#define IDC_Q7                          1017
#define IDC_Q8                          1018
#define IDC_Q9                          1019
#define IDC_Q10                         1020
#define IDC_Q11                         1021
#define IDC_RADIO_DIRECT_ACCESS         1022
#define IDC_RADIO_1000                  1023
#define IDC_RADIO10_00V                 1024
#define IDC_RADIO_10_000V               1025
#define IDC_SLIDER_AO0                  1026
#define IDC_SLIDER_AO1                  1027
#define ID_DAC_CONST                    1030
#define ID_ADC_CONST                    1031
#define IDC_EDIT_DAC0                   1032
#define IDC_EDIT_DAC1                   1033
#define IDC_STATIC__DAC0                1034
#define IDC_STATIC__DAC1                1035
#define ID_DAC0_SET_CONST               1036
#define ID_DAC1_SET_CONST               1037
#define IDC_ADC0                        1038
#define IDC_ADC1                        1039
#define IDC_ADC3                        1040
#define IDC_ADC5                        1041
#define IDC_ADC6                        1042
#define IDC_ADC4                        1043
#define IDC_ADC2                        1044
#define IDC_ADC7                        1045
#define IDC_STATIC_ADC0                 1046
#define IDC_STATIC_ADC1                 1047
#define IDC_STATIC_ADC2                 1048
#define IDC_STATIC_ADC3                 1049
#define IDC_STATIC_ADC4                 1050
#define IDC_STATIC_ADC5                 1051
#define IDC_STATIC_ADC6                 1052
#define IDC_STATIC_ADC7                 1053
#define IDC_EDIT_ADC0_CONST             1054
#define IDC_EDIT_ADC1_CONST             1055
#define IDC_EDIT_ADC2_CONST             1056
#define IDC_EDIT_ADC3_CONST             1057
#define IDC_EDIT_ADC4_CONST             1058
#define IDC_EDIT_ADC5_CONST             1059
#define IDC_EDIT_ADC6_CONST             1060
#define IDC_EDIT_ADC7_CONST             1061
#define IDC_BUTTON_ADC0_SET_CONST       1062
#define IDC_BUTTON_ADC1_SET_CONST       1063
#define IDC_BUTTON_ADC2_SET_CONST       1064
#define IDC_BUTTON_ADC3_SET_CONST       1065
#define IDC_BUTTON_ADC4_SET_CONST       1066
#define IDC_BUTTON_ADC5_SET_CONST       1067
#define IDC_BUTTON_ADC6_SET_CONST       1068
#define IDC_BUTTON_ADC7_SET_CONST       1069
#define IDC_BUTTON_ADC_READ_CONST       1070
#define IDC_BUTTON_DAC_READ_CONST       1071
#define ID_ADC_CONST_SAVE_TO_EEPROM     1072
#define ID_DAC_CONST_SAVE_TO_EEPROM     1073
#define IDC_BUTTON_ADC_LOAD_DEF_CONST   1074
#define IDC_BUTTON_DAC_LOAD_DEF_CONST   1075
#define IDC_BUTTON_ADC_LOAD_FROM_EEPROM 1076
#define IDC_BUTTON_DAC_LOAD_FROM_EEPROM 1077
#define IDC_FB                          1078
#define IDC_FB0                         1079
#define IDC_FB1                         1080
#define IDC_FB2                         1081
#define IDC_ADI0                        1090
#define IDC_ADI1                        1091
#define IDC_ADI2                        1092
#define IDC_ADI3                        1093
#define IDC_ADI4                        1094
#define IDC_ADI5                        1095
#define IDC_ADI6                        1096
#define IDC_ADI7                        1097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11
#define _APS_NEXT_COMMAND_VALUE         27
#define _APS_NEXT_CONTROL_VALUE         51
#define _APS_NEXT_SYMED_VALUE           0
#endif
#endif
